Don't run check if the commit is a cherry-pick

diff --git a/checks/before-check b/checks/before-check
--- a/checks/before-check
+++ b/checks/before-check
@@ -3,7 +3,18 @@
 
 set -x
 
-main() {
+fail_if_cherry_pick() {
+    local message
+    message="$DRONE_COMMIT_MESSAGE"
+
+    # If commit message is in the form "module: [x.y] ...." it is considered as
+    # a cherry-pick as described in https://github.com/coopengo/coog/wiki/dev-workflow
+    echo "$DRONE_COMMIT_MESSAGE" | grep '\w+: \[[[:digit:]]+\.[[:digit:]]+\]' && \
+        echo "Cherry-pick, no test required" && exit 1
+}
+
+checkout() {
+
     local branch
     branch="$DRONE_BRANCH"
     if [ "$DRONE_REPO_NAME" = "customers" ]
